import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Iphone161(),
        ]),
      ),
    );
  }
}

class Iphone161 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(side: BorderSide(width: 1)),
            shadows: [
              BoxShadow(
                color: Color(0x3F000000),
                blurRadius: 4,
                offset: Offset(0, 4),
                spreadRadius: 0,
              )
            ],
          ),
          child: Stack(
            children: [
              Positioned(
                left: 27,
                top: 0,
                child: SizedBox(
                  width: 118,
                  height: 50,
                  child: Text(
                    '카메라 구역',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 11,
                top: 110,
                child: Container(
                  width: 361,
                  height: 1419,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 376,
                          height: 1465,
                          child: Stack(
                            children: [
                              Positioned(
                                left: -0,
                                top: 585.10,
                                child: Container(
                                  width: 376,
                                  height: 278.99,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 376,
                                          height: 278.99,
                                          decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                        ),
                                      ),
                                      Positioned(
                                        left: 13,
                                        top: 11.30,
                                        child: Container(
                                          width: 348,
                                          height: 201.06,
                                          decoration: BoxDecoration(color: Colors.black),
                                        ),
                                      ),
                                      Positioned(
                                        left: 23,
                                        top: 224.78,
                                        child: SizedBox(
                                          width: 327,
                                          height: 25.98,
                                          child: Text(
                                            '영상 제목',
                                            style: TextStyle(
                                              color: Colors.black,
                                              fontSize: 16,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 0,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 30,
                                        top: 258.66,
                                        child: SizedBox(
                                          width: 192,
                                          height: 10.17,
                                          child: Text(
                                            '영상 제작자',
                                            style: TextStyle(
                                              color: Colors.black,
                                              fontSize: 16,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 0,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: -0,
                                top: 292.55,
                                child: Container(
                                  width: 376,
                                  height: 278.99,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 376,
                                          height: 278.99,
                                          decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                        ),
                                      ),
                                      Positioned(
                                        left: 13,
                                        top: 11.30,
                                        child: Container(
                                          width: 348,
                                          height: 201.06,
                                          decoration: BoxDecoration(color: Colors.black),
                                        ),
                                      ),
                                      Positioned(
                                        left: 23,
                                        top: 224.78,
                                        child: SizedBox(
                                          width: 327,
                                          height: 25.98,
                                          child: Text(
                                            '영상 제목',
                                            style: TextStyle(
                                              color: Colors.black,
                                              fontSize: 16,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 0,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 30,
                                        top: 258.66,
                                        child: SizedBox(
                                          width: 192,
                                          height: 10.17,
                                          child: Text(
                                            '영상 제작자',
                                            style: TextStyle(
                                              color: Colors.black,
                                              fontSize: 16,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 0,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: -0,
                                top: 1186.01,
                                child: Container(
                                  width: 376,
                                  height: 278.99,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 376,
                                          height: 278.99,
                                          decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                        ),
                                      ),
                                      Positioned(
                                        left: 13,
                                        top: 11.30,
                                        child: Container(
                                          width: 348,
                                          height: 201.06,
                                          decoration: BoxDecoration(color: Colors.black),
                                        ),
                                      ),
                                      Positioned(
                                        left: 23,
                                        top: 224.78,
                                        child: SizedBox(
                                          width: 327,
                                          height: 25.98,
                                          child: Text(
                                            '영상 제목',
                                            style: TextStyle(
                                              color: Colors.black,
                                              fontSize: 16,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 0,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 30,
                                        top: 258.66,
                                        child: SizedBox(
                                          width: 192,
                                          height: 10.17,
                                          child: Text(
                                            '영상 제작자',
                                            style: TextStyle(
                                              color: Colors.black,
                                              fontSize: 16,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 0,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: -0,
                                top: 881.03,
                                child: Container(
                                  width: 376,
                                  height: 278.99,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 376,
                                          height: 278.99,
                                          decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                        ),
                                      ),
                                      Positioned(
                                        left: 13,
                                        top: 11.30,
                                        child: Container(
                                          width: 348,
                                          height: 201.06,
                                          decoration: BoxDecoration(color: Colors.black),
                                        ),
                                      ),
                                      Positioned(
                                        left: 23,
                                        top: 224.78,
                                        child: SizedBox(
                                          width: 327,
                                          height: 25.98,
                                          child: Text(
                                            '영상 제목',
                                            style: TextStyle(
                                              color: Colors.black,
                                              fontSize: 16,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 0,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 30,
                                        top: 258.66,
                                        child: SizedBox(
                                          width: 192,
                                          height: 10.17,
                                          child: Text(
                                            '영상 제작자',
                                            style: TextStyle(
                                              color: Colors.black,
                                              fontSize: 16,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 0,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 376,
                                  height: 278.99,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 376,
                                          height: 278.99,
                                          decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                        ),
                                      ),
                                      Positioned(
                                        left: 13,
                                        top: 11.30,
                                        child: Container(
                                          width: 348,
                                          height: 201.06,
                                          decoration: BoxDecoration(color: Colors.black),
                                        ),
                                      ),
                                      Positioned(
                                        left: 23,
                                        top: 224.78,
                                        child: SizedBox(
                                          width: 327,
                                          height: 25.98,
                                          child: Text(
                                            '영상 제목',
                                            style: TextStyle(
                                              color: Colors.black,
                                              fontSize: 16,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 0,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 30,
                                        top: 258.66,
                                        child: SizedBox(
                                          width: 192,
                                          height: 10.17,
                                          child: Text(
                                            '영상 제작자',
                                            style: TextStyle(
                                              color: Colors.black,
                                              fontSize: 16,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 0,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 793,
                child: Container(
                  width: 393,
                  height: 59,
                  decoration: BoxDecoration(color: Color(0xFFB4B2B2)),
                ),
              ),
              Positioned(
                left: 50,
                top: 798,
                child: Container(
                  width: 291,
                  height: 50,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 241,
                        top: 0,
                        child: Container(
                          width: 50,
                          height: 50,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: FlutterLogo(),
                        ),
                      ),
                      Positioned(
                        left: 121,
                        top: 0,
                        child: Container(
                          width: 50,
                          height: 50,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/50x50"),
                              fit: BoxFit.contain,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 50,
                          height: 50,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/50x50"),
                              fit: BoxFit.contain,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 50,
                child: Container(
                  width: 393,
                  height: 50,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 393,
                          height: 50,
                          decoration: ShapeDecoration(
                            color: Color(0xF7FF0000),
                            shape: RoundedRectangleBorder(side: BorderSide(width: 1)),
                            shadows: [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 4,
                                offset: Offset(0, 4),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 20,
                        top: 10,
                        child: SizedBox(
                          width: 86,
                          height: 30,
                          child: Text(
                            '가짜 유튜브',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 16,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 393,
                  height: 50,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 393,
                          height: 50,
                          decoration: ShapeDecoration(
                            color: Colors.black.withOpacity(0.9700000286102295),
                            shape: RoundedRectangleBorder(side: BorderSide(width: 1)),
                            shadows: [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 4,
                                offset: Offset(0, 4),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(side: BorderSide(width: 1)),
            shadows: [
              BoxShadow(
                color: Color(0x3F000000),
                blurRadius: 4,
                offset: Offset(0, 4),
                spreadRadius: 0,
              )
            ],
          ),
          child: Stack(
            children: [
              Positioned(
                left: 27,
                top: 0,
                child: SizedBox(
                  width: 118,
                  height: 50,
                  child: Text(
                    '카메라 구역',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 25,
                top: 377,
                child: SizedBox(
                  width: 223,
                  height: 46,
                  child: Text(
                    '댓글창\n',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 400,
                child: Container(
                  width: 364,
                  height: 612,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 5,
                        top: 62,
                        child: Container(
                          width: 359,
                          height: 58,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 359,
                                  height: 54,
                                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                ),
                              ),
                              Positioned(
                                left: 59,
                                top: 0,
                                child: SizedBox(
                                  width: 300,
                                  height: 54,
                                  child: Text(
                                    '댓글 내용 12345 댓글내용\n2번쨰줄 댓글 내용 댓글 내용 댓글 내용',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 14,
                                top: 8,
                                child: Container(
                                  width: 30,
                                  height: 30,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/30x30"),
                                      fit: BoxFit.contain,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 9,
                                top: 30,
                                child: SizedBox(
                                  width: 48,
                                  height: 28,
                                  child: Text(
                                    '닉네임',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 5,
                        top: 0,
                        child: Container(
                          width: 359,
                          height: 54,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 359,
                                  height: 54,
                                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                ),
                              ),
                              Positioned(
                                left: 59,
                                top: 0,
                                child: SizedBox(
                                  width: 300,
                                  height: 54,
                                  child: Text(
                                    '내가 쓸 댓글 작성 작성 작성 작성 작성',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 5,
                                top: 16,
                                child: SizedBox(
                                  width: 48,
                                  height: 28,
                                  child: Text(
                                    '내\n닉네임',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 319,
                                top: 11,
                                child: Container(
                                  width: 32,
                                  height: 32,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/32x32"),
                                      fit: BoxFit.contain,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 5,
                        top: 182,
                        child: Container(
                          width: 359,
                          height: 58,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 359,
                                  height: 54,
                                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                ),
                              ),
                              Positioned(
                                left: 59,
                                top: 0,
                                child: SizedBox(
                                  width: 300,
                                  height: 54,
                                  child: Text(
                                    '댓글 내용 12345 댓글내용\n2번쨰줄 댓글 내용 댓글 내용 댓글 내용',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 14,
                                top: 8,
                                child: Container(
                                  width: 30,
                                  height: 30,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/30x30"),
                                      fit: BoxFit.contain,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 9,
                                top: 30,
                                child: SizedBox(
                                  width: 48,
                                  height: 28,
                                  child: Text(
                                    '닉네임',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 5,
                        top: 120,
                        child: Container(
                          width: 359,
                          height: 58,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 359,
                                  height: 54,
                                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                ),
                              ),
                              Positioned(
                                left: 59,
                                top: 0,
                                child: SizedBox(
                                  width: 300,
                                  height: 54,
                                  child: Text(
                                    '댓글 내용 12345 댓글내용\n2번쨰줄 댓글 내용 댓글 내용 댓글 내용',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 14,
                                top: 8,
                                child: Container(
                                  width: 30,
                                  height: 30,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/30x30"),
                                      fit: BoxFit.contain,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 9,
                                top: 30,
                                child: SizedBox(
                                  width: 48,
                                  height: 28,
                                  child: Text(
                                    '닉네임',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 4,
                        top: 244,
                        child: Container(
                          width: 359,
                          height: 58,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 359,
                                  height: 54,
                                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                ),
                              ),
                              Positioned(
                                left: 59,
                                top: 0,
                                child: SizedBox(
                                  width: 300,
                                  height: 54,
                                  child: Text(
                                    '댓글 내용 12345 댓글내용\n2번쨰줄 댓글 내용 댓글 내용 댓글 내용',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 14,
                                top: 8,
                                child: Container(
                                  width: 30,
                                  height: 30,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/30x30"),
                                      fit: BoxFit.contain,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 9,
                                top: 30,
                                child: SizedBox(
                                  width: 48,
                                  height: 28,
                                  child: Text(
                                    '닉네임',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 368,
                        child: Container(
                          width: 359,
                          height: 58,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 359,
                                  height: 54,
                                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                ),
                              ),
                              Positioned(
                                left: 59,
                                top: 0,
                                child: SizedBox(
                                  width: 300,
                                  height: 54,
                                  child: Text(
                                    '댓글 내용 12345 댓글내용\n2번쨰줄 댓글 내용 댓글 내용 댓글 내용',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 14,
                                top: 8,
                                child: Container(
                                  width: 30,
                                  height: 30,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/30x30"),
                                      fit: BoxFit.contain,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 9,
                                top: 30,
                                child: SizedBox(
                                  width: 48,
                                  height: 28,
                                  child: Text(
                                    '닉네임',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 430,
                        child: Container(
                          width: 359,
                          height: 58,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 359,
                                  height: 54,
                                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                ),
                              ),
                              Positioned(
                                left: 59,
                                top: 0,
                                child: SizedBox(
                                  width: 300,
                                  height: 54,
                                  child: Text(
                                    '댓글 내용 12345 댓글내용\n2번쨰줄 댓글 내용 댓글 내용 댓글 내용',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 14,
                                top: 8,
                                child: Container(
                                  width: 30,
                                  height: 30,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/30x30"),
                                      fit: BoxFit.contain,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 9,
                                top: 30,
                                child: SizedBox(
                                  width: 48,
                                  height: 28,
                                  child: Text(
                                    '닉네임',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 4,
                        top: 306,
                        child: Container(
                          width: 359,
                          height: 58,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 359,
                                  height: 54,
                                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                ),
                              ),
                              Positioned(
                                left: 59,
                                top: 0,
                                child: SizedBox(
                                  width: 300,
                                  height: 54,
                                  child: Text(
                                    '댓글 내용 12345 댓글내용\n2번쨰줄 댓글 내용 댓글 내용 댓글 내용',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 14,
                                top: 8,
                                child: Container(
                                  width: 30,
                                  height: 30,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/30x30"),
                                      fit: BoxFit.contain,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 9,
                                top: 30,
                                child: SizedBox(
                                  width: 48,
                                  height: 28,
                                  child: Text(
                                    '닉네임',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 430,
                        child: Container(
                          width: 359,
                          height: 58,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 359,
                                  height: 54,
                                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                ),
                              ),
                              Positioned(
                                left: 59,
                                top: 0,
                                child: SizedBox(
                                  width: 300,
                                  height: 54,
                                  child: Text(
                                    '댓글 내용 12345 댓글내용\n2번쨰줄 댓글 내용 댓글 내용 댓글 내용',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 14,
                                top: 8,
                                child: Container(
                                  width: 30,
                                  height: 30,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/30x30"),
                                      fit: BoxFit.contain,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 9,
                                top: 30,
                                child: SizedBox(
                                  width: 48,
                                  height: 28,
                                  child: Text(
                                    '닉네임',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 492,
                        child: Container(
                          width: 359,
                          height: 58,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 359,
                                  height: 54,
                                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                ),
                              ),
                              Positioned(
                                left: 59,
                                top: 0,
                                child: SizedBox(
                                  width: 300,
                                  height: 54,
                                  child: Text(
                                    '댓글 내용 12345 댓글내용\n2번쨰줄 댓글 내용 댓글 내용 댓글 내용',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 14,
                                top: 8,
                                child: Container(
                                  width: 30,
                                  height: 30,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/30x30"),
                                      fit: BoxFit.contain,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 9,
                                top: 30,
                                child: SizedBox(
                                  width: 48,
                                  height: 28,
                                  child: Text(
                                    '닉네임',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 4,
                        top: 306,
                        child: Container(
                          width: 359,
                          height: 58,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 359,
                                  height: 54,
                                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                ),
                              ),
                              Positioned(
                                left: 59,
                                top: 0,
                                child: SizedBox(
                                  width: 300,
                                  height: 54,
                                  child: Text(
                                    '댓글 내용 12345 댓글내용\n2번쨰줄 댓글 내용 댓글 내용 댓글 내용',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 14,
                                top: 8,
                                child: Container(
                                  width: 30,
                                  height: 30,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/30x30"),
                                      fit: BoxFit.contain,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 9,
                                top: 30,
                                child: SizedBox(
                                  width: 48,
                                  height: 28,
                                  child: Text(
                                    '닉네임',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 4,
                        top: 368,
                        child: Container(
                          width: 359,
                          height: 58,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 359,
                                  height: 54,
                                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                ),
                              ),
                              Positioned(
                                left: 59,
                                top: 0,
                                child: SizedBox(
                                  width: 300,
                                  height: 54,
                                  child: Text(
                                    '댓글 내용 12345 댓글내용\n2번쨰줄 댓글 내용 댓글 내용 댓글 내용',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 14,
                                top: 8,
                                child: Container(
                                  width: 30,
                                  height: 30,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/30x30"),
                                      fit: BoxFit.contain,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 9,
                                top: 30,
                                child: SizedBox(
                                  width: 48,
                                  height: 28,
                                  child: Text(
                                    '닉네임',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 430,
                        child: Container(
                          width: 359,
                          height: 58,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 359,
                                  height: 54,
                                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                ),
                              ),
                              Positioned(
                                left: 59,
                                top: 0,
                                child: SizedBox(
                                  width: 300,
                                  height: 54,
                                  child: Text(
                                    '댓글 내용 12345 댓글내용\n2번쨰줄 댓글 내용 댓글 내용 댓글 내용',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 14,
                                top: 8,
                                child: Container(
                                  width: 30,
                                  height: 30,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/30x30"),
                                      fit: BoxFit.contain,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 9,
                                top: 30,
                                child: SizedBox(
                                  width: 48,
                                  height: 28,
                                  child: Text(
                                    '닉네임',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 492,
                        child: Container(
                          width: 359,
                          height: 58,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 359,
                                  height: 54,
                                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                ),
                              ),
                              Positioned(
                                left: 59,
                                top: 0,
                                child: SizedBox(
                                  width: 300,
                                  height: 54,
                                  child: Text(
                                    '댓글 내용 12345 댓글내용\n2번쨰줄 댓글 내용 댓글 내용 댓글 내용',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 14,
                                top: 8,
                                child: Container(
                                  width: 30,
                                  height: 30,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/30x30"),
                                      fit: BoxFit.contain,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 9,
                                top: 30,
                                child: SizedBox(
                                  width: 48,
                                  height: 28,
                                  child: Text(
                                    '닉네임',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 492,
                        child: Container(
                          width: 359,
                          height: 58,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 359,
                                  height: 54,
                                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                ),
                              ),
                              Positioned(
                                left: 59,
                                top: 0,
                                child: SizedBox(
                                  width: 300,
                                  height: 54,
                                  child: Text(
                                    '댓글 내용 12345 댓글내용\n2번쨰줄 댓글 내용 댓글 내용 댓글 내용',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 14,
                                top: 8,
                                child: Container(
                                  width: 30,
                                  height: 30,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/30x30"),
                                      fit: BoxFit.contain,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 9,
                                top: 30,
                                child: SizedBox(
                                  width: 48,
                                  height: 28,
                                  child: Text(
                                    '닉네임',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 554,
                        child: Container(
                          width: 359,
                          height: 58,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 359,
                                  height: 54,
                                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                                ),
                              ),
                              Positioned(
                                left: 59,
                                top: 0,
                                child: SizedBox(
                                  width: 300,
                                  height: 54,
                                  child: Text(
                                    '댓글 내용 12345 댓글내용\n2번쨰줄 댓글 내용 댓글 내용 댓글 내용',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 14,
                                top: 8,
                                child: Container(
                                  width: 30,
                                  height: 30,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/30x30"),
                                      fit: BoxFit.contain,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 9,
                                top: 30,
                                child: SizedBox(
                                  width: 48,
                                  height: 28,
                                  child: Text(
                                    '닉네임',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 2,
                top: 304,
                child: Container(
                  width: 392,
                  height: 66,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 392,
                          height: 66,
                          decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                        ),
                      ),
                      Positioned(
                        left: 13,
                        top: 10,
                        child: SizedBox(
                          width: 330,
                          height: 36,
                          child: Text(
                            '영상 제목',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 14,
                        top: 36,
                        child: SizedBox(
                          width: 234,
                          height: 30,
                          child: Text(
                            '영상 업로드 인물/영상 업로드 날짜',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 793,
                child: Container(
                  width: 393,
                  height: 59,
                  decoration: BoxDecoration(color: Color(0xFFB4B2B2)),
                ),
              ),
              Positioned(
                left: 50,
                top: 798,
                child: Container(
                  width: 291,
                  height: 50,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 241,
                        top: 0,
                        child: Container(
                          width: 50,
                          height: 50,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: FlutterLogo(),
                        ),
                      ),
                      Positioned(
                        left: 121,
                        top: 0,
                        child: Container(
                          width: 50,
                          height: 50,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/50x50"),
                              fit: BoxFit.contain,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 50,
                          height: 50,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/50x50"),
                              fit: BoxFit.contain,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 393,
                  height: 50,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 393,
                          height: 50,
                          decoration: ShapeDecoration(
                            color: Colors.black.withOpacity(0.9700000286102295),
                            shape: RoundedRectangleBorder(side: BorderSide(width: 1)),
                            shadows: [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 4,
                                offset: Offset(0, 4),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 50,
                child: Container(
                  width: 395,
                  height: 254,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 1,
                        top: -1,
                        child: Container(
                          width: 394,
                          height: 255,
                          decoration: BoxDecoration(color: Color(0xFF3C3C3C)),
                        ),
                      ),
                      Positioned(
                        left: 60,
                        top: 50,
                        child: SizedBox(
                          width: 262,
                          height: 123,
                          child: Text(
                            '영 상',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 16,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(side: BorderSide(width: 1)),
            shadows: [
              BoxShadow(
                color: Color(0x3F000000),
                blurRadius: 4,
                offset: Offset(0, 4),
                spreadRadius: 0,
              )
            ],
          ),
          child: Stack(
            children: [
              Positioned(
                left: 27,
                top: 0,
                child: SizedBox(
                  width: 118,
                  height: 50,
                  child: Text(
                    '카메라 구역',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 70,
                child: Container(
                  width: 355,
                  height: 706,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 355,
                          height: 706,
                          decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                        ),
                      ),
                      Positioned(
                        left: 20.71,
                        top: 49.12,
                        child: Container(
                          width: 281.04,
                          height: 25.81,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: SizedBox(
                                  width: 88.75,
                                  height: 24.98,
                                  child: Text(
                                    '영상 제목',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 72.97,
                                top: 0.83,
                                child: Container(
                                  width: 208.07,
                                  height: 24.98,
                                  decoration: BoxDecoration(color: Colors.white),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 20.71,
                        top: 83.25,
                        child: Container(
                          width: 291.89,
                          height: 24.98,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: SizedBox(
                                  width: 88.75,
                                  height: 24.98,
                                  child: Text(
                                    '업로드 유저',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 83.82,
                                top: -0,
                                child: Container(
                                  width: 208.07,
                                  height: 24.98,
                                  decoration: BoxDecoration(color: Colors.white),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 9.86,
                        top: 8.33,
                        child: SizedBox(
                          width: 335.28,
                          height: 33.30,
                          child: Text(
                            '영상 업로드',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 125,
                top: 710,
                child: Container(
                  width: 145,
                  height: 50,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
              Positioned(
                left: 50,
                top: 230,
                child: Container(
                  width: 290,
                  height: 184,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
              Positioned(
                left: 145,
                top: 290,
                child: SizedBox(
                  width: 190,
                  height: 70,
                  child: Text(
                    '올릴 영상 업로드',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 161,
                top: 721,
                child: SizedBox(
                  width: 70,
                  height: 27,
                  child: Text(
                    'SUBMIT',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 793,
                child: Container(
                  width: 393,
                  height: 59,
                  decoration: BoxDecoration(color: Color(0xFFB4B2B2)),
                ),
              ),
              Positioned(
                left: 50,
                top: 798,
                child: Container(
                  width: 291,
                  height: 50,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 241,
                        top: 0,
                        child: Container(
                          width: 50,
                          height: 50,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: FlutterLogo(),
                        ),
                      ),
                      Positioned(
                        left: 121,
                        top: 0,
                        child: Container(
                          width: 50,
                          height: 50,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/50x50"),
                              fit: BoxFit.contain,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 50,
                          height: 50,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/50x50"),
                              fit: BoxFit.contain,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 393,
                  height: 50,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 393,
                          height: 50,
                          decoration: ShapeDecoration(
                            color: Colors.black.withOpacity(0.9700000286102295),
                            shape: RoundedRectangleBorder(side: BorderSide(width: 1)),
                            shadows: [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 4,
                                offset: Offset(0, 4),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}